env:
  global:
    - CC_TEST_REPORTER_ID=42c331f97b916004bf08bfbf903de06c0b55c4c4c4a4dff6f0207d7aff230d45
language: ruby
rvm:
  - 2.4.4
  - 2.5.1
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
before_script:
  - export WPXF_ENV=test
  - bundle exec rake db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
branches:
  except:
    - gh-pages
